filebeat.inputs:
  - type: filestream
    id: davrods-upload-log
    enabled: true
    paths:
      - /var/log/apache2/apache.access.log
      - /var/log/apache2/apache.error.log
      - /var/log/apache2/apache.audit.log
    parsers:
      - ndjson:
          keys_under_root: true
          add_error_key: true
          overwrite_keys: true
    tags: ["DAVRODSUPLOAD"]

# Disable filebeat monitoring  
logging.metrics.enabled: false

output.logstash:
  hosts: ["elk.dh.local:5044"]
