filebeat.inputs:
  - type: log
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true
    enabled: true
    paths:
      - /var/log/apache2/apache.access.log
      - /var/log/apache2/apache.error.log
      - /var/log/apache2/apache.audit.log
    tags: ["DAVRODS"]

# Disable filebeat monitoring  
logging.metrics.enabled: false

output.logstash:
  hosts: ["elk.dh.local:5044"]
